# openapi/concierge.yaml

openapi: 3.0.0

servers:
- url: /api
info:
  title: Searchy Concierge Service
  version: '1.0'
  description: >
    API responsible for responding to user inputs.
paths:
  /feeder:
    post:
      description: |
        Register new document to be indexed
      responses:
        '200':
          description: |
            Register new document to be indexed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
        '400':
          description: >
            request was not processed because payload was incomplete or incorrect
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/document'
  /query:
    post:
      description: |
        search query
      responses:
        '200':
          description: |
            Response consists of links to document
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
components:
  schemas:
    response:
      type: object
      properties:
        code:
          type: integer
          description: Status code to send in response
        msg:
          type: string
          description: message to send out
    document:
      type: object
      required:
      - title
      - link
      properties:
        title:
          type: string
          description: Title of the document
        link:
          type: string
          description: link to the document.